#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# GNOME Adam Internet Applet
# Copyright 2009 Joel Stanley <joel@jms.id.au>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
import gtk
import pygtk
pygtk.require('2.0')

import gnomeapplet

import adamlib

def adam_factory(applet, iid):
    """
    Creates an Adam Usage Meter Applet
    """

    adamlib.AdamMeter(applet, iid)
    return True


if len(sys.argv) == 2 and sys.argv[1] == "--window":
    # Launch the applet in its own window
    main_window = gtk.Window(gtk.WINDOW_TOPLEVEL)
    main_window.set_title("Adam")
    main_window.connect("destroy", gtk.main_quit)

    app = gnomeapplet.Applet()
    adam_factory(app, None)
    app.reparent(main_window)
    main_window.show_all()

    gtk.main()
    sys.exit()
else:
    # Launch the applet through the bonobo interfaces (as a panel applet)
    gnomeapplet.bonobo_factory("OAFIID:AdamUsageMeterApplet_Factory",
        gnomeapplet.Applet.__gtype__, "adam", "0", adam_factory)

